# Generated by Django 5.1 on 2024-08-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosBasicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
    ]
